"""Extraction against a committed fixture PDF, with a scripted model. No network.

The fixture is generated by `make_fixture.py` **with the real document's pathology**: its
glyphs are kerned far enough apart that every extractor inserts spaces between them, so
`document_text` on it comes back as "P u n j a b  C l e a n  A i r". That is not an
inconvenience the test works around — it is the condition the guard has to work under, and
a clean fixture would let an exact string match pass and prove nothing.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from terrarium.policy import extract as extract_module
from terrarium.policy.extract import ExtractionUnavailable, document_text, extract
from terrarium.policy.schema import Coverage, PolicyMeasure, despace

FIXTURE = Path(__file__).resolve().parent / "fixture_policy.pdf"

# Verbatim from `make_fixture.LINES`. What a model reading the *rendered* page would copy.
REAL_QUOTE = (
    "Establish a low emission zone removing 36 percent of vehicle emissions in the "
    "central district by 2030."
)
GREENING_QUOTE = (
    "Increase urban tree canopy cover by 25 percent across the metropolitan area "
    "through a sustained plantation drive."
)
FUEL_QUOTE = "Reduce sulfur content in diesel fuel to 10 parts per million"


class FakeGemini:
    """Stands in for `GeminiAdapter`, which is what `_pdf_reader` looks for by type."""

    name = "fake-gemini:test"

    def __init__(self, payload: object) -> None:
        self.payload = payload
        self.pdfs: list[bytes] = []

    def complete_json_with_pdf(self, *, system: str, user: str, pdf: bytes) -> str:
        self.pdfs.append(pdf)
        return json.dumps(self.payload)


def _measure(**overrides: object) -> dict[str, object]:
    base = {
        "title": "Low emission zone in the central district",
        "sector": "transport",
        "target": "36 percent of vehicle emissions",
        "target_year": 2030,
        "source_page": 1,
        "quote": REAL_QUOTE,
    }
    return {**base, **overrides}


def _extract(
    payload: object, monkeypatch: pytest.MonkeyPatch
) -> tuple[tuple[tuple[PolicyMeasure, ...], Coverage], FakeGemini]:
    adapter = FakeGemini(payload)
    monkeypatch.setattr(extract_module, "_pdf_reader", lambda _adapter: adapter)
    monkeypatch.setattr(extract_module, "resolve_adapter", lambda _s, **_kw: adapter)
    return extract(FIXTURE.read_bytes(), document="fixture", settings=object()), adapter


# --- the pathology the guard exists for ---------------------------------------------


def test_the_fixture_really_is_shredded_on_extraction() -> None:
    """Guard the fixture. If this ever passes cleanly, the fixture has stopped
    reproducing the failure and every test below is passing for the wrong reason."""
    from pypdf import PdfReader

    raw = "".join(page.extract_text() or "" for page in PdfReader(str(FIXTURE)).pages)

    assert "Punjab Clean Air" not in raw, "the fixture no longer reproduces the shredding"
    assert "P u n j a b" in raw


def test_despacing_makes_the_shredded_text_comparable_again() -> None:
    haystack = document_text(FIXTURE.read_bytes())

    assert despace(REAL_QUOTE) in haystack
    assert despace("Punjab Clean Air Action Plan") in haystack


# --- the guard ------------------------------------------------------------------------


def test_a_real_quote_survives(monkeypatch: pytest.MonkeyPatch) -> None:
    (measures, coverage), adapter = _extract({"measures": [_measure()]}, monkeypatch)

    assert len(measures) == 1
    assert measures[0].sector == "transport"
    assert coverage.extracted == 1 and coverage.grounded == 1
    assert coverage.expressible == 1
    # The PDF bytes went to the model, not extracted text. That is the whole design.
    assert adapter.pdfs[0].startswith(b"%PDF")


def test_a_fabricated_quote_is_dropped(monkeypatch: pytest.MonkeyPatch) -> None:
    """The assertion this module exists for. The measure reads perfectly well and its
    quote appears nowhere in the document, which is indistinguishable from invention."""
    invented = _measure(
        title="Ban all motorcycles within the ring road",
        quote="All motorcycles shall be prohibited within the ring road from 2027 onwards.",
    )
    (measures, coverage), _ = _extract({"measures": [_measure(), invented]}, monkeypatch)

    assert [m.title for m in measures] == ["Low emission zone in the central district"]
    assert coverage.extracted == 2
    assert coverage.grounded == 1
    # Reported rather than merely absent: a silently filtered fabrication is a
    # fabrication nobody knows the model produced.
    assert len(coverage.dropped_quotes) == 1
    assert "motorcycles" in coverage.dropped_quotes[0]


def test_a_paraphrased_quote_is_dropped(monkeypatch: pytest.MonkeyPatch) -> None:
    """The realistic failure, not the dramatic one. A model that tidies a quote has
    stopped quoting, and there is no way to tell a tidied quote from an invented one."""
    paraphrased = _measure(
        quote="Establish a low-emission zone that removes 36% of vehicle emissions "
        "in the central district by the year 2030."
    )
    (measures, coverage), _ = _extract({"measures": [paraphrased]}, monkeypatch)

    assert measures == ()
    assert coverage.grounded == 0


def test_whitespace_differences_do_not_drop_a_good_quote(monkeypatch: pytest.MonkeyPatch) -> None:
    """The other direction, and the reason `despace` is not simply strict matching: a
    quote read off the rendered page has different spacing from the extracted text by
    construction, and rejecting it would drop every measure in the document."""
    spaced = _measure(quote="Establish  a low emission zone   removing 36 percent")
    (measures, _), _ = _extract({"measures": [spaced]}, monkeypatch)

    assert len(measures) == 1


def test_a_malformed_measure_is_skipped_not_fatal(monkeypatch: pytest.MonkeyPatch) -> None:
    (measures, coverage), _ = _extract(
        {"measures": [{"title": "x"}, _measure()]}, monkeypatch
    )

    assert len(measures) == 1
    assert coverage.extracted == 2


def test_the_digest_ties_a_measure_to_the_exact_bytes(monkeypatch: pytest.MonkeyPatch) -> None:
    (measures, _), _ = _extract({"measures": [_measure()]}, monkeypatch)
    assert len(measures[0].document_sha256) == 64


# --- coverage, which is the output that matters --------------------------------------


def test_the_miss_rate_is_reported_not_filtered(monkeypatch: pytest.MonkeyPatch) -> None:
    """Most of a clean-air plan cannot be said with two levers. Printing only the
    measures that fit would describe a document this tool understands far better than
    it does."""
    payload = {
        "measures": [
            _measure(),
            _measure(
                title="Increase urban tree canopy cover",
                sector="urban_greening",
                target="25 percent",
                quote=GREENING_QUOTE,
            ),
            _measure(
                title="Reduce sulfur content in diesel fuel",
                sector="industry",
                target="10 parts per million",
                quote=FUEL_QUOTE,
            ),
        ]
    }
    (_measures, coverage), _ = _extract(payload, monkeypatch)

    assert coverage.grounded == 3
    # The fuel standard is a real commitment with no lever for it.
    assert coverage.expressible == 2
    assert "3 measures extracted" in coverage.summary
    assert "2 expressible on this tile" in coverage.summary
    assert "not measures that failed to extract" in coverage.summary


def test_no_pdf_capable_model_refuses_rather_than_half_extracting(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """The one path in this project with no offline fallback, and it says so.

    A rule parser cannot read a policy document, and the extracted text above is far too
    mangled to parse meaning from — so refusing is the honest answer, exactly as
    `scripts/validate_air.py` refuses without an OpenAQ key.
    """
    monkeypatch.setattr(extract_module, "resolve_adapter", lambda _s, **_kw: None)

    with pytest.raises(ExtractionUnavailable) as excinfo:
        extract(FIXTURE.read_bytes(), document="fixture", settings=object())

    message = str(excinfo.value)
    assert "TERRARIUM_GEMINI_API_KEY" in message
    # And it says why this does not break the zero-budget claim.
    assert "build step" in message


def test_is_grounded_in_rejects_a_quote_that_is_too_short() -> None:
    """A twenty-character floor. "the" appears in every document, and a measure whose
    quote is a common fragment would pass the guard while grounding nothing."""
    haystack = document_text(FIXTURE.read_bytes())
    assert not PolicyMeasure(
        title="x" * 5,
        sector="other",
        target="",
        quote="a" * 20,
        document="fixture",
        document_sha256="0" * 64,
    ).is_grounded_in(haystack)
